### ISSUE TITLE
Paths with spaces are not accepted on windows for the build settings

### ISSUE THREAD

**Issue by Anticept** [DeeUnderscore/atom-build-dm#1]
See these screenshots. Even tried encapsulating with quotes in the settings.

![image](https://user-images.githubusercontent.com/521038/46346835-6a9cab80-c617-11e8-9b86-eb0f4dfcd1eb.png)

![image](https://user-images.githubusercontent.com/521038/46346842-712b2300-c617-11e8-9573-74e6b736bf7e.png)

**Comment by DeeUnderscore** [comment]
Hi, sorry for not looking at this earlier.

I'm not sure if this isn't an upstream issue—see noseglid/atom-build#380.

**Comment by Anticept** [comment]
I... don't even remember this issue.

I had started using the dm langserver anyways and it works fine.
